version: '3.8'
services:
  docker-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3006"
    volumes:
      - ./src:/react/next-gen/src
    env_file:
      - ./.env
    container_name: dockertestcont
    image: dokcertest:tag
    