version: '3.8'
services:
  docker-test:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=React
    ports:
      - "80:3006"
    env_file:
      - ./.env
    container_name: dockertestcont
    image: dokcertest:tag
    